INCLUDE(CheckCXXCompilerFlag)


CHECK_CXX_COMPILER_FLAG(-Werror=unknown-warning-option COMPILER_SUPPORTS_WARNING_ERROR_UNKNOWN_WARNING_OPTION)
if(COMPILER_SUPPORTS_WARNING_ERROR_UNKNOWN_WARNING_OPTION)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror=unknown-warning-option")
endif()

CHECK_CXX_COMPILER_FLAG(-Wmissing-braces COMPILER_SUPPORTS_WARNING_MISSING_BRACES)
if(COMPILER_SUPPORTS_WARNING_MISSING_BRACES)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wmissing-braces")
endif()

CHECK_CXX_COMPILER_FLAG(-Wnon-virtual-dtor COMPILER_SUPPORTS_WARNING_NON_VIRTUAL_DTOR)
if(COMPILER_SUPPORTS_WARNING_NON_VIRTUAL_DTOR)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wnon-virtual-dtor")
endif()

CHECK_CXX_COMPILER_FLAG(-Woverloaded-virtual COMPILER_SUPPORTS_WARNING_OVERLOADED_VIRTUAL)
if(COMPILER_SUPPORTS_WARNING_OVERLOADED_VIRTUAL)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Woverloaded-virtual")
endif()

CHECK_CXX_COMPILER_FLAG(-Wreorder COMPILER_SUPPORTS_WARNING_REORDER)
if(COMPILER_SUPPORTS_WARNING_REORDER)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wreorder")
endif()

CHECK_CXX_COMPILER_FLAG(-Wsign-compare COMPILER_SUPPORTS_WARNING_SIGN_COMPARE)
if(COMPILER_SUPPORTS_WARNING_SIGN_COMPARE)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wsign-compare")
endif()

CHECK_CXX_COMPILER_FLAG(-Wunused-local-typedefs COMPILER_SUPPORTS_WARNING_UNUSED_LOCAL_TYPEDEFS)
if(COMPILER_SUPPORTS_WARNING_UNUSED_LOCAL_TYPEDEFS)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wunused-local-typedefs")
endif()

CHECK_CXX_COMPILER_FLAG(-Wunused-variable COMPILER_SUPPORTS_WARNING_UNUSED_VARIABLE)
if(COMPILER_SUPPORTS_WARNING_UNUSED_VARIABLE)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wunused-variable")
endif()

CHECK_CXX_COMPILER_FLAG(-Wvla COMPILER_SUPPORTS_WARNING_VLA)
if(COMPILER_SUPPORTS_WARNING_VLA)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wvla")
endif()


set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror")

